<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <RootNamespace>MyModules</RootNamespace>
	  <TargetFramework>net10.0-windows</TargetFramework>
	  <OutputType>Library</OutputType>
	  <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>C:\Project\StudyLogs\exe\debug</OutputPath>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>C:\Project\StudyLogs\exe\release</OutputPath>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

</Project>
